version: "3.8"
services:
  mongodb:
    image: mongo:4.4
    restart: on-failure
    container_name: mongodb
    volumes: 
      - /var/volumes/mongo-data:/data/db


  oanda_bigquery:
    build: ./services/oanda_bigquery
    image: eu.gcr.io/brushed-charts/oanda_bigquery:${PROFIL}-latest
    restart: on-failure
    container_name: oanda_bigquery 
    env_file: 
      - ./env/services.env
      - ./env/services.${PROFIL}.env
    volumes: 
      - type: bind
        source: /etc/brushed-charts/
        target: /etc/brushed-charts/


  oanda_fetcher:
    build: ./services/oanda_fetcher
    image: eu.gcr.io/brushed-charts/oanda_fetcher:${PROFIL}-latest
    restart: on-failure
    container_name: oanda_fetcher
    env_file: 
      - ./env/services.env
      - ./env/oanda_secret.env
      - ./env/services.${PROFIL}.env
    volumes: 
      - type: bind
        source: /etc/brushed-charts/
        target: /etc/brushed-charts/


  oanda_history:
    build: ./services/oanda_history
    image: eu.gcr.io/brushed-charts/oanda_history:${PROFIL}-latest
    restart: on-failure
    container_name: oanda_history
    env_file: 
      - ./env/services.env
      - ./env/services.${PROFIL}.env
    volumes: 
      - type: bind
        source: /etc/brushed-charts/
        target: /etc/brushed-charts/


  oanda_watchlist:
    build: ./services/oanda_watchlist
    image: eu.gcr.io/brushed-charts/oanda_watchlist:${PROFIL}-latest
    restart: on-failure
    container_name: oanda_watchlist
    env_file: 
      - ./env/services.env
      - ./env/services.${PROFIL}.env
    volumes: 
      - type: bind
        source: /etc/brushed-charts/
        target: /etc/brushed-charts/


  oanda_clean_history:
    build: ./services/oanda_clean_history
    image: eu.gcr.io/brushed-charts/oanda_clean_history:${PROFIL}-latest
    restart: on-failure
    container_name: oanda_clean_history
    env_file: 
      - ./env/services.env
      - ./env/services.${PROFIL}.env
    volumes: 
        source: /etc/brushed-charts/
        target: /etc/brushed-charts/
        